version: '2'

services:
    web:
        image: nginx:latest
        build:
          context: .
          dockerfile: Dockerfile-nginx
        ports:
            - "80:80"
        volumes:
            - ./config/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:5.6-fpm
        build:
          context: .
          dockerfile: Dockerfile-php
        volumes:
            - ./config/php.ini:/usr/local/etc/php/php.ini
        networks:
            - code-network
    mongodb:
        image: mongo
        ports:
          - "27017:27017"
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
