FROM php:5.6-fpm
COPY ./code /code
RUN apt-get update && apt-get install -y \
    autoconf g++ make openssl libssl-dev \
    libcurl4-openssl-dev pkg-config libsasl2-dev libpcre3-dev \
    zip unzip \
    && pecl install mongo \
    && echo "extension=mongo.so" > /usr/local/etc/php/conf.d/mongo.ini \
    && curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony \
    && chmod a+x /usr/local/bin/symfony \
    && mkdir /code/app/cache/prod \
    && chmod -R 777 /code/app/cache \
