<?php

namespace Neo\NasaBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * NeoRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class NeoRepository extends DocumentRepository
{
  private $neo;

  public function __construct(Neo $neo)
  {
    $this->neo = $neo;
  }
  public function create()
  {

    $dm = $this->get('doctrine_mongodb')->getManager();
    $dm->getSchemaManager()->ensureIndexes();
    $dm->persist($this->neo);
    try {
        $dm->flush();
    } catch (MongoCursorException $e) {
        return new Response('Already exists');
    }
  }

}
