<?php

namespace Neo\NasaBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * NewRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class NewRepository extends DocumentRepository
{
}