# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    ## guzzle http client
    guzzle:
        class: Guzzle\Http\Client
        arguments: ['%nasa_service.endpoint%']

    neo.document:
        class: Neo\NasaBundle\Document\Neo

    neo.fetchData:
        class: Neo\NasaBundle\Service\NasaWebService
        arguments:
          - @guzzle
          - '%nasa_service.api_key%'

    neo.fastFacts:
      class: 'Neo\NasaBundle\Service\FastFacts'
      arguments: ["@=service('doctrine.odm.mongodb.document_manager').getRepository('NasaBundle:Neo')"]
